#Global configuration
spring:

  application:
    name: pay-my-buddy
    #H2 Configuration
    h2.console.enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paymybudy
    username: root
    password: smashed31
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  servlet:
    context-path: /paymybuddy

#Log level configuration
logging:
  level:
    error: DEBUG


